paart/apps/common/urls.py
from django.conf.urls.defaults import patterns, url
from django.views.generic.simple import direct_to_template
from django.conf import settings

urlpatterns = patterns('common.views',
    url(r'^about/$', direct_to_template, {'template': 'about.html'}, 'about_view'),
    url(r'^license/$', 'license_view', (), 'license_view'),
    url(r'^password/change/done/$', 'password_change_done', (), name='password_change_done'),
    url(r'^object/multiple/action/$', 'multi_object_action_view', (), name='multi_object_action_view'),

    url(r'^user/$', 'current_user_details', (), 'current_user_details'),
    url(r'^user/edit/$', 'current_user_edit', (), 'current_user_edit'),

    url(r'^login/$', 'login_view', (), name='login_view'),
    url(r'^password/change/$', 'password_change_view', (), name='password_change_view'),
)

urlpatterns += patterns('',
    url(r'^logout/$', 'django.contrib.auth.views.logout', {'next_page': '/'}, name='logout_view'),

    url(r'^password/reset/$', 'django.contrib.auth.views.password_reset', {'email_template_name': 'password_reset_email.html', 'template_name': 'password_reset_form.html', 'post_reset_redirect': '/password/reset/done'}, name='password_reset_view'),
    url(r'^password/reset/confirm/(?P<uidb36>[0-9A-Za-z]+)-(?P<token>.+)/$', 'django.contrib.auth.views.password_reset_confirm', {'template_name': 'password_reset_confirm.html', 'post_reset_redirect': '/password/reset/complete/'}, name='password_reset_confirm_view'),
    url(r'^password/reset/complete/$', 'django.contrib.auth.views.password_reset_complete', {'template_name': 'password_reset_complete.html'}, name='password_reset_complete_view'),
    url(r'^password/reset/done/$', 'django.contrib.auth.views.password_reset_done', {'template_name': 'password_reset_done.html'}, name='password_reset_done_view'),

    (r'^favicon\.ico$', 'django.views.generic.simple.redirect_to', {'url': '%s%s' % (settings.STATIC_URL, 'images/favicon.ico')}),
)

urlpatterns += patterns('',
    url(r'^set_language/$', 'django.views.i18n.set_language', name='set_language'),
)

paart/apps/main/urls.py
from django.conf.urls.defaults import patterns, url

urlpatterns = patterns('main.views',
    url(r'^$', 'home', (), 'home'),
)

paart/apps/reports/urls.py
from __future__ import absolute_import

from django.conf.urls.defaults import patterns, url

urlpatterns = patterns('reports.views',
    url(r'^$', 'agency_search_report', (), 'agency_search_report')
)

paart/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),

    # Mayan apps
    (r'^', include('main.urls')),
    (r'^common/', include('common.urls')),
    (r'^project_setup/', include('project_setup.urls')),
    (r'^project_tools/', include('project_tools.urls')),
    (r'^acls/', include('acls.urls')),
    #(r'^search/', include('dynamic_search.urls')),
    (r'^settings/', include('smart_settings.urls')),
    (r'^permissions/', include('permissions.urls')),
    (r'^user_management/', include('user_management.urls')),

    # Project
    (r'^agencies/', include('agencies.urls')),
    (r'^projects/', include('projects.urls')),
    (r'^telecomm/', include('telecomm.urls')),
    #(r'^infrastructure/', include('infrastructure.urls')),
    #(r'^tools/', include('tools.urls')),
    (r'^data/', include('data.urls')),
    (r'^software/', include('software.urls')),
    (r'^api/', include('api.urls')),
    
    # Reports
    (r'^reports/', include('reports.urls')),
)   

if settings.DEVELOPMENT:
    if 'rosetta' in settings.INSTALLED_APPS:
        urlpatterns += patterns('',
            url(r'^rosetta/', include('rosetta.urls'), name='rosetta'),
        )

paart/apps/reports/models.py
from django.db import models

# Create your models here.

paart/apps/common/forms.py
from __future__ import absolute_import

import os

from django import forms
from django.conf import settings
from django.contrib.auth import authenticate
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.models import User
from django.db import models
from django.forms.widgets import Select, SelectMultiple
from django.utils.translation import ugettext_lazy as _

import django_select2

from .utils import return_attrib
from .widgets import (DetailSelectMultiple, PlainWidget, TextAreaDiv,
    EmailInput)


class DetailForm(forms.ModelForm):
    def __init__(self, extra_fields=None, *args, **kwargs):
        super(DetailForm, self).__init__(*args, **kwargs)
        if extra_fields:
            for extra_field in extra_fields:
                result = return_attrib(self.instance, extra_field['field'])
                label = 'label' in extra_field and extra_field['label'] or None
                #TODO: Add others result types <=> Field types
                if isinstance(result, models.query.QuerySet):
                    self.fields[extra_field['field']] = \
                        forms.ModelMultipleChoiceField(
                            queryset=result, label=label)
                else:
                    self.fields[extra_field['field']] = forms.CharField(
                        label=extra_field['label'],
                        initial=return_attrib(self.instance,
                            extra_field['field'], None),
                            widget=PlainWidget)

        for field_name, field in self.fields.items():
            if isinstance(field.widget, forms.widgets.SelectMultiple):
                self.fields[field_name].widget = DetailSelectMultiple(
                    choices=field.widget.choices,
                    attrs=field.widget.attrs,
                    queryset=getattr(field, 'queryset', None),
                )
                self.fields[field_name].help_text = ''
            elif isinstance(field.widget, forms.widgets.Select):
                self.fields[field_name].widget = DetailSelectMultiple(
                    choices=field.widget.choices,
                    attrs=field.widget.attrs,
                    queryset=getattr(field, 'queryset', None),
                )
                #self.fields[field_name].help_text = ''

        for field_name, field in self.fields.items():
            self.fields[field_name].help_text = ''
            self.fields[field_name].widget.attrs.update({'readonly': 'readonly'})


class GenericConfirmForm(forms.Form):
    def __init__(self, *args, **kwargs):
        pass


class GenericAssignRemoveForm(forms.Form):
    def __init__(self, *args, **kwargs):
        left_list_qryset = kwargs.pop('left_list_qryset', None)
        right_list_qryset = kwargs.pop('right_list_qryset', None)
        left_filter = kwargs.pop('left_filter', None)
        super(GenericAssignRemoveForm, self).__init__(*args, **kwargs)
        if left_filter:
            self.fields['left_list'].queryset = left_list_qryset.filter(
                *left_filter)
        else:
            self.fields['left_list'].queryset = left_list_qryset

        self.fields['right_list'].queryset = right_list_qryset

    left_list = forms.ModelMultipleChoiceField(required=False, queryset=None)
    right_list = forms.ModelMultipleChoiceField(required=False, queryset=None)


class FilterForm(forms.Form):
    def __init__(self, list_filters, *args, **kwargs):
        super(FilterForm, self).__init__(*args, **kwargs)
        for list_filter in list_filters:
            label = list_filter.get('title', list_filter['name'])
            self.fields[list_filter['name']] = forms.ModelChoiceField(
                queryset=list_filter['queryset'],
                label=label[0].upper() + label[1:], required=False)


class ChoiceForm(forms.Form):
    """
    Form to be used in side by side templates used to add or remove
    items from a many to many field
    """
    def __init__(self, *args, **kwargs):
        choices = kwargs.pop('choices', [])
        label = kwargs.pop('label', _(u'Selection'))
        super(ChoiceForm, self).__init__(*args, **kwargs)
        self.fields['selection'].choices = choices
        self.fields['selection'].label = label
        self.fields['selection'].widget.attrs.update({'size': 14, 'class': 'choice_form'})

    selection = forms.MultipleChoiceField()


class UserForm_view(DetailForm):
    """
    Form used to display an user's public details
    """
    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'is_staff', 'is_superuser', 'last_login', 'date_joined', 'groups')


class UserForm(forms.ModelForm):
    """
    Form used to edit an user's mininal fields by the user himself
    """
    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email')


class EmailAuthenticationForm(AuthenticationForm):
    """
    Override the default authentication form to use email address
    authentication
    """
    email = forms.CharField(label=_(u'Email'), max_length=75,
        widget=EmailInput(attrs={'style': 'width: 100%;'})
    )

    def clean(self):
        email = self.cleaned_data.get('email')
        password = self.cleaned_data.get('password')

        if email and password:
            self.user_cache = authenticate(email=email, password=password)
            if self.user_cache is None:
                raise forms.ValidationError(_('Please enter a correct email and password. Note that the password fields is case-sensitive.'))
            elif not self.user_cache.is_active:
                raise forms.ValidationError(_('This account is inactive.'))
        self.check_for_test_cookie()
        return self.cleaned_data

# Remove the inherited username field
EmailAuthenticationForm.base_fields.keyOrder = ['email', 'password']


class FileDisplayForm(forms.Form):
    text = forms.CharField(
        label='',  # _(u'Text'),
        widget=forms.widgets.Textarea(
            attrs={'cols': 40, 'rows': 20, 'readonly': 'readonly'}
        )
    )

    def __init__(self, *args, **kwargs):
        super(FileDisplayForm, self).__init__(*args, **kwargs)
        changelog_path = os.path.join(settings.PROJECT_ROOT, os.sep.join(self.DIRECTORY), self.FILENAME)
        fd = open(changelog_path)
        self.fields['text'].initial = fd.read()
        fd.close()


class LicenseForm(FileDisplayForm):
    FILENAME = u'LICENSE'
    DIRECTORY = [u'..']


# I used this instead of lambda expression after scope problems
def _get_cleaner(form, field):
    def clean_field():
         return getattr(form.instance, field, None)
    return clean_field


class ROFormMixin(forms.BaseForm):
    def __init__(self, *args, **kwargs):
        super(ROFormMixin, self).__init__(*args, **kwargs)
        if hasattr(self, 'readonly_fields'):
            if self.instance and self.instance.pk:
                for field in self.readonly_fields:
                    self.fields[field].required = False
                    self.fields[field].widget.attrs['readonly'] = True
                    self.fields[field].widget.attrs['disabled'] = True
                    setattr(self, 'clean_' + field, _get_cleaner(self, field))


class Select2FormMixin(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(Select2FormMixin, self).__init__(*args, **kwargs)    
        for name, field in self.fields.items():
            if isinstance(field.widget, SelectMultiple):
                old_dict = field.widget.__dict__
                field.widget = django_select2.widgets.Select2MultipleWidget(select2_options={'width': '400px'})
                field.widget.__dict__.update(old_dict)
                field.help_text = ''
            elif isinstance(field.widget, Select):
                old_dict = field.widget.__dict__
                field.widget = django_select2.widgets.Select2Widget(select2_options={'width': '400px'})
                field.widget.__dict__.update(old_dict)

paart/apps/reports/forms.py
# -*- coding: utf-8 -*- 

from __future__ import absolute_import

from django import forms
from django.utils.translation import ugettext_lazy as _

from agencies.models import Agency
from projects.models import (ProjectInfo, FiscalYear, Purpose, Classification, 
Methodology, Department, Goal)


class AgencySearchForm(forms.Form):
    agency_text = forms.CharField(required=False, label=_('Agency'))
    project_text = forms.CharField(required=False, label=_('Project'))
    fiscal_year = forms.ModelChoiceField(required=False, queryset=FiscalYear.objects.all(), label=_('Fiscal Year'))
    purpose = forms.ModelChoiceField(required=False, queryset=Purpose.objects.all(), label=_('Purpose'))
    classification = forms.ModelChoiceField(required=False, queryset=Classification.objects.all(), label=_('Classification'))
    secondary_classification = forms.ModelChoiceField(required=False, queryset=Classification.objects.all(), label=_('Secondary Classification'))
    methodology = forms.ModelChoiceField(required=False, queryset=Methodology.objects.all(), label=_('Methodology'))
    department = forms.ModelChoiceField(required=False, queryset=Department.objects.all(), label=_('Department'))
    goal = forms.ModelChoiceField(required=False, queryset=Goal.objects.all(), label=_('Goals'))
    date_from = forms.DateField(required=False, input_formats=['%m/%d/%Y'],  widget=forms.TextInput(attrs={'class': 'datepicker'}), label=_('Date From'))
    date_to = forms.DateField(required=False, input_formats=['%m/%d/%Y'], widget=forms.TextInput(attrs={'class': 'datepicker'}), label=_('Date to'))

paart/apps/reports/views.py
# -*- coding: utf-8 -*-

from __future__ import absolute_import

import datetime
import pytz

from django.conf import global_settings
from django.shortcuts import render_to_response
from django.template import RequestContext
from django.utils.translation import ugettext_lazy as _
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.core.exceptions import PermissionDenied

from projects.models import Project, ProjectInfo, Agency

from acls.models import AccessEntry
from permissions.models import Permission
from .permissions import PERMISSION_PROJECT_VIEW

from .forms import AgencySearchForm


def agency_search_report(request):
    kwargs = {}
    context = {}
    localtz = pytz.timezone(global_settings.TIME_ZONE)

    if request.GET:
        form = AgencySearchForm(data=request.GET)
        if form.is_valid():
            if 'agency_text' in request.GET and request.GET['agency_text']:
                kwargs['agency__name__icontains'] = request.GET['agency_text']

            if 'project_text'in request.GET and request.GET['project_text']:
                kwargs['label__icontains'] = request.GET['project_text']

            if 'fiscal_year' in request.GET and request.GET['fiscal_year']:
                kwargs['projectinfo__fiscal_year'] = request.GET['fiscal_year']

            if 'purpose' in request.GET and request.GET['purpose']:
                kwargs['projectinfo__purpose'] = request.GET['purpose']

            if 'classification' in request.GET and request.GET['classification']:
                kwargs['projectinfo__classification'] = request.GET['classification']

            if 'secondary_classification' in request.GET and request.GET['secondary_classification']:
                kwargs['projectinfo__classification_secondary'] = request.GET['secondary_classification']

            if 'methodology' in request.GET and request.GET['methodology']:
                kwargs['projectinfo__methodology'] = request.GET['methodology']

            if 'goal' in request.GET and request.GET['goal']:
                kwargs['projectinfo__goals__in'] = request.GET['goal']

            if 'department' in request.GET and request.GET['department']:
                kwargs['projectinfo__department'] = request.GET['department']

            if 'date_from' in request.GET and request.GET['date_from']:
                date_from = datetime.datetime.strptime(request.GET['date_from'], '%m/%d/%Y')
                kwargs['datetime_created__gte'] = date_from.replace(tzinfo=localtz)

            if 'date_to' in request.GET and request.GET['date_to']:
                date_to = datetime.datetime.strptime(request.GET['date_to'], '%m/%d/%Y')
                kwargs['datetime_created__lte'] = date_to.replace(tzinfo=localtz)

            try:
                Permission.objects.check_permissions(request.user, [PERMISSION_PROJECT_VIEW])
            except PermissionDenied:
                # If user doesn't have global permission, get a list of document
                # for which he/she does have access use it to filter the
                # provided object_list
                search_results = AccessEntry.objects.filter_objects_by_access(PERMISSION_PROJECT_VIEW, request.user,
                                                                              Project.objects.filter(**kwargs).order_by('agency__name'),
                                                                              related='agency')
            else:
                search_results = Project.objects.filter(**kwargs).order_by('agency__name')

            if not search_results:
                context['message'] = _(u'No results')
            else:
                paginator = Paginator(search_results, 25)
                page = request.GET.get('page')
                try:
                    context['results'] = paginator.page(page)
                except PageNotAnInteger:
                    context['results'] = paginator.page(1)
                except EmptyPage:
                    context['results'] = paginator.page(paginator.num_pages)

        context['agency_search_form'] = form
    else:
        context.update({
            'agency_search_form': AgencySearchForm(),
        })

    return render_to_response('agency_search.html', context, context_instance=RequestContext(request))

paart/apps/common/templates/agency_result_row.html
<tr>
    <th> {{ desc }} </th> 
    <td> {{ content|default:"No data" }} </td>
</tr>

paart/apps/common/templates/generic_assign_remove.html
{% extends "base.html" %}
{% load i18n %}
{% block title %} :: {% blocktrans %}Assign {{ title }} {{ object }}{% endblocktrans %}{% endblock %}


{% block content %}
    <style>
        #id_right_list,#id_left_list { min-width: 28em; min-height: 13em; }
    </style>
    <div class="content">   
    <h2 class="title">{{ title|safe }}</h2>
    
    <form method='POST' action='' id='assign_remove'>{% csrf_token %}
        <input name='action' value='' type='hidden' />
         <table>
            <tbody>
                <tr>
                    <th style='text-align:center;'>{{ left_list_title }}</th><td></td><th style='text-align:center;'>{{ right_list_title }}</th>
                </tr>
                <tr>
                    <td>
                        {{ form.left_list }}{{ form.left_list.errors }}
                    </td>
                    <td>
                        <table>
                            <tbody>
                                <tr>
                                  <td><button class="button" onclick='document.forms["assign_remove"].action.value="assign";document.forms["assign_remove"].submit();'>&gt;</button></td>
                                </tr>
                                <tr>
                                  <td><button class="button" onclick='document.forms["assign_remove"].action.value="remove";document.forms["assign_remove"].submit();'>&lt;</button></td>
                                </tr>
                            </tbody>					
                        </table>
                    </td>
                    <td>{{ form.right_list }}{{ form.right_list.errors }}</td>
                </tr>
                {{ form.media|safe }}			
            </tbody>
        </table>
    </form>
    </div>
{% endblock %}

paart/apps/common/templates/generic_detail.html
{% extends "base.html" %}
{% load i18n %}
{% load subtemplates_tags %}

{% block title %} :: {% with "true" as read_only %}{% with "true" as striptags %}{% include "calculate_form_title.html" %}{% endwith %}{% endwith %}{% endblock %}

{% block sidebar %}
    {% for subtemplate in sidebar_subtemplates %}
        <div class="generic_subform">
            {% include subtemplate %}
        </div>        
    {% endfor %}
  
    {% for subtemplate in sidebar_subtemplates_list %}
        {% with "true" as side_bar %}
            {% if subtemplate.form %}
                {% render_subtemplate subtemplate.name subtemplate.context as rendered_subtemplate %}
                {% with "true" as read_only %}
                    <div class="generic_subform">
                        {{ rendered_subtemplate }}
                    </div>
                {% endwith %}
            {% else %}
                {% render_subtemplate subtemplate.name subtemplate.context as rendered_subtemplate %}
                {{ rendered_subtemplate }}
            {% endif %}
                </div>
                {% if subtemplate.grid_clear or not subtemplate.grid %}
                    <div class=""></div> 
            {% endif %}
        {% endwith %}
    {% endfor %}     
{% endblock %}

{% block stylesheets %}
    <style type="text/css">
        #subform form  textarea, 
        #subform form  select option,
        #subform form  input, 
        #subform form  select, 
        #subform form  input { background: none; color: black; border: none; }
    </style>
{% endblock %}

{% block content %}
    {% if form %}
        {% with "true" as read_only %}
            <div class="">
                <div class="generic_subform">
                    {% include "generic_form_subtemplate.html" %}
                </div>
            </div>
            {% if grid_clear or not grid %}
                <div class=""></div> 
            {% endif %}
        {% endwith %}
    {% endif %}
    
    <div class="container_12">
        {% for subtemplate in subtemplates_list %}
            <div class="grid_{{ subtemplate.grid|default:12 }}">       
                {% with "true" as read_only %}
                    {% render_subtemplate subtemplate.name subtemplate.context as rendered_subtemplate %}
                    <div class="generic_subform">
                        {{ rendered_subtemplate }}
                    </div>
                {% endwith %}
            </div>
            {% if subtemplate.grid_clear or not subtemplate.grid %}
                <div class="clear"></div> 
            {% endif %}
         {% endfor %}
    </div>    
    
{% endblock %}

paart/apps/common/templates/generic_form.html
{% extends "base.html" %}
{% load subtemplates_tags %}

{% block title %} :: {% with "true" as striptags %}{% include "calculate_form_title.html" %}{% endwith %}{% endblock %}

{% block sidebar %}
    {% for subtemplate in sidebar_subtemplates_list %}
        {% if subtemplate.form %}
            {% render_subtemplate subtemplate.name subtemplate.context as rendered_subtemplate %}
                <div class="generic_subform">
                    {{ rendered_subtemplate }}
                </div>
        {% else %}
            {% render_subtemplate subtemplate.name subtemplate.context as rendered_subtemplate %}
            {{ rendered_subtemplate }}
        {% endif %}
            {% if subtemplate.grid_clear or not subtemplate.grid %}
            {% endif %}
    {% endfor %}
{% endblock %}

{% block content %}
    {% if form %}
        <div class="generic_subform">
            {% include "generic_form_subtemplate.html" %}
        </div>
    {% endif %}
                             
<div class="container_12">
    {% for subtemplate in subtemplates_list %}
        <div class="grid_{{ subtemplate.grid|default:12 }}">       
            {% if subtemplate.form %}
                {% render_subtemplate subtemplate.name subtemplate.context as rendered_subtemplate %}
                    <div class="generic_subform">
                        {{ rendered_subtemplate }}
                    </div>
            {% else %}
                {% render_subtemplate subtemplate.name subtemplate.context as rendered_subtemplate %}
                {{ rendered_subtemplate }}
            {% endif %}
        </div>
        {% if subtemplate.grid_clear or not subtemplate.grid %}
            <div class="clear"></div> 
        {% endif %}
     {% endfor %}
</div>
{% endblock %}

paart/apps/common/templates/generic_form_instance.html
{% load i18n %}
{% load styling %}
{{ form.media|safe }}  
{% add_classes_to_form form %}

{% if form.non_field_errors %}
    <div class="flash">
        {% for value in form.non_field_errors %}
            <div class="message error">
                <p>{{ value }}</p>
            </div>
      {% endfor %}                    
  </div>
{% endif %}

{% if form_display_mode_table %}
    {% for field in form.hidden_fields %}
        {{ field }}
    {% endfor %}
    <tr class="{% cycle 'odd' 'even2' %}">
    {% for field in form.visible_fields %}
            <td title="{% if field.errors %}{% for error in field.errors %}{{ error }}{% if not forloop.last %} | {% endif %}{% endfor %}{% else %}{{ field.help_text }}{% endif %}">
            {% if field.errors %}<div class="flash"><div class="error">{% endif %}
              {{ field }}
            {% if field.errors %}</div></div>{% endif %}
            </td>
    {% endfor %} 
    </tr>
{% else %}
    {% for field in form.hidden_fields %}
        {{ field }}
    {% endfor %}
    
    {% for field in form.visible_fields %}
        <div class="group">
            {% if field.errors %}<div class="fieldWithErrors">{% endif %}
            <label class="label">{{ field.label_tag }}{% if field.field.required and not read_only and not form_hide_required_text %} *{% endif %}</label>
            {% if field.errors %}<span class="error">{% for error in field.errors %}{{ error }}{% if not forloop.last %} | {% endif %}{% endfor %}</span></div>{% endif %} 
            {{ field }}
            {% if field.help_text %}<br /><span class="description">{{ field.help_text }}</span>{% endif %}
        </div>
    {% endfor %} 
{% endif %}

paart/apps/common/templates/generic_list_horizontal.html
{% extends "base.html" %}
{% load i18n %}
{% load navigation_tags %}
{% load subtemplates_tags %}

{% block title %} :: {% blocktrans with title|striptags as stripped_title %}List of {{ stripped_title }}{% endblocktrans %}{% endblock %}
{#{% block secondary_links %}{{ secondary_links|safe }}{% endblock %}#}

{% block sidebar %}
    {% for subtemplate in sidebar_subtemplates_list %}
        {% if subtemplate.form %}
            {% render_subtemplate subtemplate.name subtemplate.context as rendered_subtemplate %}
                <div class="generic_subform">
                    {{ rendered_subtemplate }}
                </div>
        {% else %}
            {% render_subtemplate subtemplate.name subtemplate.context as rendered_subtemplate %}
            {{ rendered_subtemplate }}
        {% endif %}
     {% endfor %}

{% endblock %}

{% block content %}
    {% include "generic_list_horizontal_subtemplate.html" %}

{% endblock %}

paart/apps/common/templates/generic_subtemplate.html
{% if side_bar %}
    <div class="block">
        <h3>{{ title|capfirst }}</h3>
        <div class="content">
{% else %}
    <div class="content">    
        <h2 class="title">{{ title|capfirst }}</h2>
        <div class="inner">
{% endif %}

{% if content %}
    <p>{{ content|safe }}</p>
{% endif %}

{% for paragraph in paragraphs %}
    <p>{{ paragraph|safe }}</p>
{% endfor %}

</div></div>

paart/apps/common/templates/generic_template.html
{% extends "base.html" %}
{% block title %} :: {{ title|capfirst }}{% endblock %}

{% block content %}
    {% include "generic_subtemplate.html" %}
{% endblock %}

paart/apps/common/templates/generic_wizard.html
{% extends "base.html" %}
{% load i18n %}
{% load styling %}
{% add_classes_to_form form %}

{% block head %}
{{ wizard.form.media }}
{% endblock %}

{% block content %}
{% load common_default_icons_tags %}
{% default_icons %}

{% if side_bar %}
    <div class="block">
    <h3>
{% else %}
    <div class="content">
    <h2 class="title">
{% endif %}

Step {{ wizard.steps.step1 }} of {{ wizard.steps.count }}: {{ step_title }}

{% if side_bar %}
    </h3>
    <div class="content">
        <p>
{% else %}
    </h2>
    <div class="inner">
{% endif %}

{% if form.is_multipart %}
    <form name="{{ form.prefix }}" enctype="multipart/form-data" method="{{ submit_method|default:'post' }}" action="{{ form_action }}" class="form">
{% else %}
    <form name="{{ form.prefix }}" method="{{ submit_method|default:'post' }}" action="{{ form_action }}" class="form">
{% endif %}
{% csrf_token %}
    <table>
        {{ wizard.management_form }}
        {% if wizard.form.forms %}
            {{ wizard.form.management_form }}
            {% for form in wizard.form.forms %}
                {{ form }}
            {% endfor %}
        {% else %}
        {% with wizard.form as form %}
            {% include "generic_form_instance.html" %}
        {% endwith %}
        {% endif %}
    </table>
    {% if wizard.steps.prev %}
        <button class="button" type="submit" name="wizard_goto_step" value="{{ wizard.steps.first }}">{% trans "first step" %}</button>
        <button class="button" type="submit" name="wizard_goto_step" value="{{ wizard.steps.first }}">{% trans "previous step" %}</button>
    {% endif %}
    <button class="button" type="submit" value="{% trans 'submit' %}"/>
        {% if submit_icon %}
            {{ submit_icon.display_small }}
        {% else %}
            {{ icon_submit_default.display_small }}
        {% endif %}

        {% if submit_label %}{{ submit_label }}{% else %}{% if object %}{% trans "Save" %}{% else %}{% trans "Submit" %}{% endif %}{% endif %}
    </button>
</form>
{% if side_bar %}
    </p></div><!--end content--></div><!--end block-->
{% else %}
    </div></div>
{% endif %}

{% endblock %}

paart/apps/common/templates/login.html
{% extends "web_theme_login.html" %}
{% load i18n %}
{% load project_tags %}

{% block html_title %}{% project_name %} :: {% trans "Login" %}{% endblock %}
{% block project_name %}{% project_name %}{% endblock %}

paart/apps/common/templates/password_change_done.html
{% extends "base.html" %}
{% load i18n %}
{% block title %} :: {% trans "Password change" %}{% endblock %}
{% block content %}
    <h2>{% trans "Your password has been successfully changed." %}</h2>
{% endblock %}